on: push

jobs:
  e2e_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Start Python Static Server
        # Starts a server on port 8000 in the background
        run: |
          python3 -m http.server 8000 &

      - name: Install Python dependencies
        run: pip install -r .\test\requirements.txt

      - name: Run E2E Tests with Pytest and Selenium
        run: python .\test\basic_test.py